tema/Models/DetallesTecnico.cs
using System.ComponentModel.DataAnnotations;

namespace tema.Models
{
    public class DetallesTecnico
    {
        public int IDTecnico { get; set; }
        [Display(Name = "Dirección")]
        [Required(ErrorMessage = "Debe ingresar una dirección")]
        public string direccion { get; set; }
        [Display(Name = "Número telefónico")]
        [StringLength(25, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string telefono { get; set; }
        [Display(Name = "Correo")]
        [EmailAddress(ErrorMessage = "No se ingresó un correo válido")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Debe ingresar el correo")]
        [StringLength(35, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string correo { get; set; }
        public int codDet { get; set; }
        [StringLength(25, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string telefonoExt { get; set; }
    }
}

tema/Controllers/DetallesTecnicoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using tema.Models;
using tema.Models.ViewModels;

namespace tema.Controllers
{
    [Authorize]
    public class DetallesTecnicoController : Controller
    {
        string baseurl = "https://localhost:44300/";

        [Authorize]
        [Authorize(Roles = "manager")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(int id, [Bind("IDTecnico,direccion,telefono,telefonoExt,correo")] DetallesTecnico dtt)
        {
            DetallesTecnico dttPost;
            string tel = string.Empty;
            if (string.IsNullOrEmpty(dtt.telefono) && !string.IsNullOrEmpty(dtt.telefonoExt)) tel = dtt.telefonoExt;
            if (!string.IsNullOrEmpty(dtt.telefono) && string.IsNullOrEmpty(dtt.telefonoExt)) tel = dtt.telefono;
            else if (tel == string.Empty) ModelState.AddModelError("", "El campo de teléfono está vacío");
            if (ModelState.IsValid)
            {
                using (HttpClient cliente = new HttpClient())
                {
                    dttPost = new DetallesTecnico
                    {
                        IDTecnico = id,
                        direccion = dtt.direccion,
                        telefono = tel,
                        correo = dtt.correo
                    };
                    cliente.BaseAddress = new Uri(baseurl);
                    string myContent = JsonConvert.SerializeObject(dttPost);
                    byte[] buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                    ByteArrayContent byteContent = new ByteArrayContent(buffer);
                    byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    HttpResponseMessage postTask = cliente.PostAsync("Taller/Tecnico/RegistrarDetallesTecnico", byteContent).Result;
                    HttpResponseMessage result = postTask;

                    if(result.StatusCode == HttpStatusCode.Conflict)
                    {
                        ModelState.AddModelError(string.Empty, "Este correo ya le pertenece a un técnico");
                    }

                    if (result.StatusCode == HttpStatusCode.InternalServerError)
                    {
                        ModelState.AddModelError(string.Empty, "El correo o el teléfono ya existen para otro técnico");
                    }

                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index", "Tecnico");
                    }
                }
            }
            return View(dtt);
        }

        [Authorize]
        [Authorize(Roles = "manager")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            DttEditViewModel dtt = await GetDetalleEdit(id, new DttEditViewModel());
            if (dtt == null) return NotFound();
            return View(dtt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, [Bind("direccion,telefono,correo,codDet")] DttEditViewModel dtt)
        {
            if (id != dtt.codDet) return NotFound();
            if (ModelState.IsValid)
            {
                DetallesTecnico dttPatch = new DetallesTecnico
                {
                    direccion = dtt.direccion,
                    telefono = dtt.telefono,
                    correo = dtt.correo,
                    codDet = dtt.codDet
                };
                using (HttpClient cliente = new HttpClient())
                {
                    cliente.BaseAddress = new Uri(baseurl);
                    string myContent = JsonConvert.SerializeObject(dttPatch);
                    byte[] buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                    ByteArrayContent byteContent = new ByteArrayContent(buffer);
                    byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    HttpResponseMessage postTask = cliente.PatchAsync("Taller/Tecnico/ActualizarDetalles/" + id, byteContent).Result;
                    HttpResponseMessage result = postTask;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index", "Tecnico");
                    }

                    if (result.StatusCode == HttpStatusCode.InternalServerError)
                    {
                        ModelState.AddModelError(string.Empty, "El correo o el teléfono ya existen para otro técnico");
                    }
                }
            }
            return View(dtt);
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null) return null;
            if (ModelState.IsValid)
            {
                using (HttpClient cliente = new HttpClient())
                {
                    cliente.BaseAddress = new Uri(baseurl);
                    HttpResponseMessage deleteTask = await cliente.DeleteAsync
                    (
                        "Taller/Tecnico/BorrarDetallesTecnico/" + id
                    );
                }
            }
            return RedirectToAction("Index", "Tecnico");
        }

        #region bloqueConsultas
        private async Task<DetallesTecnico> GetDetalle(int? id, DetallesTecnico aux)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync
                    (
                        "Taller/Tecnico/ObtenerDetalleIndividual/" + id
                    );
                if (res.IsSuccessStatusCode)
                {
                    string auxRes = res.Content.ReadAsStringAsync().Result;
                    aux = JsonConvert.DeserializeObject<DetallesTecnico>(auxRes);
                }
            }
            return aux;
        }

        private async Task<DttEditViewModel> GetDetalleEdit(int? id, DttEditViewModel aux)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync
                    (
                        "Taller/Tecnico/ObtenerDetalleIndividual/" + id
                    );
                if (res.IsSuccessStatusCode)
                {
                    string auxRes = res.Content.ReadAsStringAsync().Result;
                    aux = JsonConvert.DeserializeObject<DttEditViewModel>(auxRes);
                }
            }
            return aux;
        }
        #endregion bloqueConsultas
    }
}

tema/Views/DetallesTecnico/Create.cshtml
@model tema.Models.DetallesTecnico

@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js" onload="window.$ = window.jQuery = module.exports;"></script>
<script>
    $(document).ready(function () {
        $("select").change(function () {
            $("select option:selected").each(function () {
                if ($(this).attr("value") == "nac") {
                    $("#extranjero").addClass("d-none");
                    $("#ninguna").addClass("d-none");
                    $("#nacional").removeClass("d-none");
                    $('#boton_guardar').addClass("d-none");
                    $('#numero_ext').val("");
                }
                if ($(this).attr("value") == "ext") {
                    $("#nacional").addClass("d-none");
                    $("#ninguna").addClass("d-none");
                    $("#extranjero").removeClass("d-none");
                    $('#boton_guardar').removeClass("d-none");
                    $('#numero_nac').val("");
                }
                if ($(this).attr("value") == "escoja") {
                    $("#nacional").addClass("d-none");
                    $("#extranjero").addClass("d-none");
                    $("#ninguna").removeClass("d-none");
                    $('#boton_guardar').addClass("d-none");
                    $('#numero_nac').val("");
                    $('#numero_ext').val("");
                }
            });
        }).change();
    });

    $(document).ready(function () {
        var $regexname = /(506-[0-9]{4}-[0-9]{4})/;
        $('#numero_nac').on('keypress keydown keyup mouseout mouseover', function () {
            if (!$(this).val().match($regexname)) {
                $('#error_msg').removeClass('d-none');
                $('#error_msg').addClass('text-danger');
                $('#boton_guardar').addClass('d-none');
            }
            else {
                $('#error_msg').addClass('d-none');
                $('#error_msg').removeClass('text-danger');
                $('#boton_guardar').removeClass('d-none');
            }
        });
    });
</script>
<div class="content-wrapper">
    <div class="container">
        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a asp-controller="DetallesTecnico" asp-action="Index" style="color:aliceblue">Detalles del técnico&nbsp;/&nbsp;</a></li>
            <li><a class="active" style="color:aliceblue">Ingresar detalles del técnico</a></li>
        </ol>
        <h1>Ingresar detalles</h1>

        <h4>Detalles del técnico</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="direccion" class="control-label"></label>
                        <input asp-for="direccion" type="text" class="form-control" /> <!--dirección-->
                        <span asp-validation-for="direccion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="telefono" class="control-label"></label>
                        <div>
                            <select class="form-control">
                                <!--Bloque selección de validaciones-->
                                <option value="escoja">Escoja el formato</option>
                                <option value="nac">Nacional (con formato)</option>
                                <option value="ext">Extranjero (sin formato)</option>
                            </select>
                        </div>
                        <div id="ninguna" class="d-none">
                            <label class="control-label text-danger">No se seleccionó ninguna opción</label>
                        </div>
                        <div id="nacional" class="d-none">
                            <!--Nacional-->
                            <label class="control-label">Ingrese un número nacional</label>
                            <input id="numero_nac" asp-for="telefono" type="text" class="form-control" />
                            <p><span id="error_msg" class="text-danger d-none">Formato inválido (ingrese el número así: 506-0000-0000)</span></p>
                        </div>
                        <div id="extranjero" class="d-none">
                            <!--Extranjero-->
                            <label class="control-label">Ingrese un número extranjero</label>
                            <input id="numero_ext" asp-for="telefonoExt" type="text" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="correo" class="control-label"></label>
                        <input asp-for="correo" type="text" class="form-control" /> <!--Correo-->
                        <span asp-validation-for="correo" class="text-danger"></span>
                    </div>
                    <button id="boton_guardar" type="submit" class="Boton d-none">Guardar</button>&nbsp;|
                    <a asp-controller="Tecnico" asp-action="Index" class="Boton">Regresar</a>

                </form>
            </div>
        </div>
       </div>
</div>

tema/Views/DetallesTecnico/Edit.cshtml
@model tema.Models.ViewModels.DttEditViewModel

@{
    ViewData["Title"] = "Actualizar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<div class="content-wrapper">
    <div class="container">
        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a asp-controller="DetallesTecnico" asp-action="Index" style="color:aliceblue">Detalles del técnico&nbsp;/&nbsp;</a></li>
            <li><a class="active" style="color:aliceblue">Actualizar detalles del técnico</a></li>
            @*<li><a href="#">Home</a></li>
                <li><a href="#">Private</a></li>
                <li><a href="#">Pictures</a></li>
                <li class="active">Vacation</li>*@
        </ol>
        <h1>Actualizar</h1>

        <h4>Detalles del técnico</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group" hidden>
                        <label asp-for="IDTecnico" class="control-label"></label>
                        <input asp-for="IDTecnico" class="form-control" />
                        <span asp-validation-for="IDTecnico" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="direccion" class="control-label"></label>
                        <input asp-for="direccion" class="form-control" />
                        <span asp-validation-for="direccion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="telefono" class="control-label"></label>
                        <input asp-for="telefono" class="form-control" />
                        <span asp-validation-for="telefono" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="correo" class="control-label"></label>
                        <input asp-for="correo" class="form-control" />
                        <span asp-validation-for="correo" class="text-danger"></span>
                    </div>
                    <div class="form-group" hidden>
                        <label asp-for="codDet" class="control-label"></label>
                        <input asp-for="codDet" class="form-control" />
                        <span asp-validation-for="codDet" class="text-danger"></span>
                    </div>
                    <input type="submit" value="Guardar" class="Boton" />&nbsp;|
                    <a asp-controller="Tecnico" asp-action="Index" class="Boton">Regresar</a>

                </form>
            </div>
        </div>

    </div>
</div>