tema/Models/Cita.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace tema.Models
{
    public class Cita
    {
        public int IDCita { get; set; }
        [Required(ErrorMessage = "No se ingresó el código del técnico. Puede obtenerlo en el módulo de técnicos")]
        [Display(Name = "Código del técnico")]
        public int? IDTecnico { get; set; }
        //[RegularExpression(@"[1-7]-[0-9]{4}-[0-9]{4}",
        //    ErrorMessage = "Formato requerido (0-0000-0000)")]
        //[Required(ErrorMessage = "No se ingresó la cédula del cliente")]
        [Display(Name = "Cédula")]
        //[StringLength(30, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string cedulaCliente { get; set; }
        [Required(ErrorMessage = "No se ingresó la fecha")]
        [Display(Name = "Fecha")]
        public DateTime? fecha { get; set; }
        [Required(ErrorMessage = "No se ingresó la hora")]
        [Display(Name = "Hora")]
        public string hora { get; set; }
        [Required(ErrorMessage = "No se ingresó el asunto")]
        [Display(Name = "Asunto")]
        [StringLength(100, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string asunto { get; set; }
        [Required(ErrorMessage = "No se ingresó una descripción")]
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }
        [Display(Name = "¿Cita confirmada?")]
        public bool citaConfirmada { get; set; }
        public int IDCliente { get; set; }
    }
}

tema/Controllers/CitaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Reflection;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using tema.Models;
using tema.Models.ViewModels;
using tema.Utilidades;

namespace tema.Controllers
{
    [Authorize]
    public class CitaController : Controller
    {
        string baseurl = "https://localhost:44300/"; 
        IHttpContextAccessor _httpContextAccessor;
        MethodBase mb = MethodBase.GetCurrentMethod();

        /*Necesito esta variable para conservar la descripción de la cita a editar*/
        string descripcionAnterior = string.Empty; 

        public CitaController(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
           //string usuario = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name).Value;
        }

        public async Task<IActionResult> Index()
        {
            CitaViewModel ctavm = new CitaViewModel();
            using (HttpClient cliente = new HttpClient())
            {
                cliente.BaseAddress = new Uri(baseurl);
                cliente.DefaultRequestHeaders.Clear();
                cliente.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage resCita = await cliente.GetAsync("Taller/Cita/ListaCitas");
                HttpResponseMessage resServicio = await cliente.GetAsync("Taller/Servicio/ListaServicios");
                HttpResponseMessage resVhl = await cliente.GetAsync("Taller/Vehiculo/ListaVehiculos");
                if (resCita.IsSuccessStatusCode && resServicio.IsSuccessStatusCode && resVhl.IsSuccessStatusCode)
                {
                    var auxResCita = resCita.Content.ReadAsStringAsync().Result;
                    var auxResServicio = resServicio.Content.ReadAsStringAsync().Result;
                    var auxResVhl = resVhl.Content.ReadAsStringAsync().Result;
                    ctavm.cita = JsonConvert.DeserializeObject<List<Cita>>(auxResCita);
                    ctavm.servicio = JsonConvert.DeserializeObject<List<Servicio>>(auxResServicio);
                    ctavm.vehiculo = JsonConvert.DeserializeObject<List<Vehiculo>>(auxResVhl);
                }
            }
            return View(ctavm);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Cita = await GetOneById(id, new Cita());
            if (Cita == null)
            {
                return NotFound();
            }

            return View(Cita);
        }
        public ActionResult Create()
        {
            return View();
        }

        //los tres métodos para poblar los selectList
        #region selectLists
        public static async Task<List<SelectListItem>> ObtenerListaTecnicos()
        {
            List<SelectListItem> ls = new List<SelectListItem>();
            HttpClient cliente = new HttpClient();
            cliente.BaseAddress = new Uri("https://localhost:44300/");
            cliente.DefaultRequestHeaders.Clear();
            cliente.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resTecnico = await cliente.GetAsync("Taller/Tecnico/ListaTecnicos");
            List<Tecnico> tnc = JsonConvert.DeserializeObject<List<Tecnico>>(await resTecnico.Content.ReadAsStringAsync());
            foreach (Tecnico temp in tnc)
            {
                ls.Add(new SelectListItem() { Text = temp.nombre + " " + temp.pmrApellido + " " + temp.sgndApellido, Value = Convert.ToString(temp.IDTecnico) });
            }
            return ls;
        }

        public static async Task<List<SelectListItem>> ObtenerListaClientes()
        {
            List<SelectListItem> ls = new List<SelectListItem>();
            HttpClient cliente = new HttpClient();
            cliente.BaseAddress = new Uri("https://localhost:44300/");
            cliente.DefaultRequestHeaders.Clear();
            cliente.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resCliente = await cliente.GetAsync("Taller/Cliente/ListaClientes");
            List<Cliente> clt = JsonConvert.DeserializeObject<List<Cliente>>(await resCliente.Content.ReadAsStringAsync());
            foreach (Cliente temp in clt)
            {
                ls.Add(new SelectListItem() { Text = temp.nombre + " " + temp.pmrApellido + " " + temp.sgndApellido + ", cédula: " + temp.cedula, Value = temp.cedula });
            }
            return ls;
        }

        public static async Task<List<SelectListItem>> ObtenerListaServicios()
        {
            List<SelectListItem> ls = new List<SelectListItem>();
            HttpClient cliente = new HttpClient();
            cliente.BaseAddress = new Uri("https://localhost:44300/");
            cliente.DefaultRequestHeaders.Clear();
            cliente.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resCliente = await cliente.GetAsync("Taller/Servicio/ListaServicios");
            List<Servicio> svc = JsonConvert.DeserializeObject<List<Servicio>>(await resCliente.Content.ReadAsStringAsync());
            foreach (Servicio temp in svc)
            {
                ls.Add(new SelectListItem() { Text = "Código del vehículo: " + temp.IDVehiculo + ", servicio: " + temp.descripcion, Value = temp.descripcion });
            }
            return ls;
        }
        #endregion selectLists 

        [HttpPost]
        public async Task<IActionResult> Create([Bind("IDTecnico,cedulaCliente,fecha,hora,asunto,descripcion,citaConfirmada")] CitaViewModel cta)
        {
            UtilidadRegistro.Registrar(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name).Value, "Cita", mb.ReflectedType.Name, "Crear");

            if(cta.hora == null)
            {
                return View(cta);
            }

            TimeSpan tiempo = TimeSpan.Parse(cta.hora);
            DateTime fechaIngresada = (DateTime)cta.fecha;
            DateTime fechaSinHora = fechaIngresada.Add(tiempo);
            DateTime fechaActual = DateTime.Now;
            DayOfWeek diaDeLaCita = cta.fecha.Value.DayOfWeek;

            if (fechaSinHora < fechaActual)
            {
                ModelState.AddModelError(string.Empty, "La fecha o la hora solicitada ya pasó");
            }

            if (tiempo < TimeSpan.Parse("07:00:00") || tiempo > TimeSpan.Parse("18:30:00"))
            {
                ModelState.AddModelError(string.Empty, "La hora solicitada es inválida");
            }

            if (diaDeLaCita == DayOfWeek.Saturday || diaDeLaCita == DayOfWeek.Sunday)
            {
                ModelState.AddModelError(string.Empty, "No se trabajan fines de semana");
            }

            Cita ctapost = new Cita
            {
                IDTecnico = cta.IDTecnico,
                cedulaCliente = cta.cedulaCliente,
                fecha = cta.fecha,
                hora = cta.hora,
                asunto = cta.asunto,
                descripcion = cta.descripcion,
                citaConfirmada = cta.citaConfirmada
            };

            if (ModelState.IsValid)
            {

                using (HttpClient cliente = new HttpClient())
                {
                    cliente.BaseAddress = new Uri(baseurl);
                    var myContent = JsonConvert.SerializeObject(ctapost);
                    var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                    var byteContent = new ByteArrayContent(buffer);
                    byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    var postTask = await cliente.PostAsync("Taller/Cita/RegistrarCita", byteContent);
                    var result = postTask;
                    if (result.StatusCode == HttpStatusCode.InternalServerError)
                    {
                        ModelState.AddModelError(string.Empty, "Este técnico ya tiene cita en la fecha y hora asignada");
                    }
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return View(cta);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Cita = await GetOneById(id, new Cita());
            if (Cita == null)
            {
                return NotFound();
            }

            descripcionAnterior = Cita.descripcion;

            return View(Cita);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, [Bind("IDCita,IDTecnico,cedulaCliente,fecha,hora,asunto,descripcion,citaConfirmada")] Cita Cita)
        {
            UtilidadRegistro.Registrar(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name).Value, "Cita", mb.ReflectedType.Name, "Editar");

            if (Cita.hora == null)
            {
                return View(Cita);
            }

            TimeSpan tiempo = TimeSpan.Parse(Cita.hora);
            DateTime fechaIngresada = (DateTime)Cita.fecha;
            DateTime fechaSinHora = fechaIngresada.Date.Add(tiempo);
            DateTime fechaActual = DateTime.Now;
            DayOfWeek diaDeLaCita = Cita.fecha.Value.DayOfWeek;

tema/Controllers/ServicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using tema.Models;
using tema.Models.ViewModels;

namespace tema.Controllers
{
    [Authorize]
    public class ServicioController : Controller
    {
        string baseurl = "https://localhost:44300/";

        public static async Task<List<SelectListItem>> ObtenerLista()
        {
            List<SelectListItem> ls = new List<SelectListItem>();
            HttpClient cliente = new HttpClient();
            cliente.BaseAddress = new Uri("https://localhost:44300/");
            cliente.DefaultRequestHeaders.Clear();
            cliente.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resVehiculo = await cliente.GetAsync("Taller/Vehiculo/ListaVehiculos");
            List<Vehiculo> vhl = JsonConvert.DeserializeObject<List<Vehiculo>>(await resVehiculo.Content.ReadAsStringAsync());
            foreach (Vehiculo temp in vhl)
            {
                ls.Add(new SelectListItem() { Text = temp.marca, Value = Convert.ToString(temp.IDVehiculo) });
            }
            return ls;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("IDVehiculo,descripcion")] Servicio svcm)
        {
            Servicio srv = new Servicio { IDVehiculo = svcm.IDVehiculo, descripcion = svcm.descripcion };
            if (ModelState.IsValid)
            {
                using (HttpClient cliente = new HttpClient())
                {
                    cliente.BaseAddress = new Uri(baseurl);
                    var myContent = JsonConvert.SerializeObject(srv);
                    var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                    var byteContent = new ByteArrayContent(buffer);
                    byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    var postTask = await cliente.PostAsync("Taller/Servicio/RegistrarServicio", byteContent);
                    var result = postTask;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index", "Cita");
                    }
                }
            }
            return View(svcm);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Servicio srv = await GetOneById(id, new Servicio());
            ServicioEdit srvedit = new ServicioEdit
            {
                IDServicio = srv.IDServicio,
                descripcion = srv.descripcion
            };
            if (srvedit == null)
            {
                return NotFound();
            }
            return View(srvedit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, [Bind("IDServicio,descripcion")] ServicioEdit servicio)
        {
            if (id != servicio.IDServicio)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(baseurl);

                    var myContent = JsonConvert.SerializeObject(servicio);
                    var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                    var byteContent = new ByteArrayContent(buffer);
                    byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    var postTask = client.PatchAsync("Taller/Servicio/ActualizarDatos/" + servicio.IDServicio, byteContent).Result;

                    var result = postTask;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index", "Cita");
                    }
                }
            }
            return View(servicio);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return null;
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(baseurl);
                    var deleteTask = client.DeleteAsync
                        (
                            "Taller/Servicio/BorrarServicio/" + id
                        );
                    deleteTask.Wait();
                }
            }
            return RedirectToAction("Index", "Cita");
        }

        private async Task<Servicio> GetOneById(int? id, Servicio aux)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync("Taller/Servicio/ListaServicios");
                if (res.IsSuccessStatusCode)
                {
                    IEnumerable<Servicio> coleccionSvc = JsonConvert.DeserializeObject<IEnumerable<Servicio>>(res.Content.ReadAsStringAsync().Result);
                    for(int k = 0;k < coleccionSvc.Count();k++)
                    {
                        IEnumerable<Servicio> svcquery = from svc in coleccionSvc where svc.IDServicio == id select svc;
                        aux = svcquery.First();
                    }
                }
            }
            return aux;
        }
    }
}

tema/Views/Cita/Create.cshtml
@model tema.Models.ViewModels.CitaViewModel

@{
    ViewData["Title"] = "Create";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<div class="content-wrapper">

    <div class="container">
        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a asp-controller="Cita" asp-action="Index" style="color:aliceblue">Citas&nbsp;/&nbsp;</a></li>
            <li><a class="active" style="color:aliceblue">Crear cita</a></li>
            @*<li><a href="#">Home</a></li>
                <li><a href="#">Private</a></li>
                <li><a href="#">Pictures</a></li>
                <li class="active">Vacation</li>*@
        </ol>
        <h1>Cita</h1>
        <h4>Crear cita</h4>
        <hr />
        <div class="row">
            <div class="col-md-6">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label class="control-label">Técnico de la cita (el nombre corresponde al código generado por el sistema)</label>
                        @Html.DropDownListFor(x => x.IDTecnico, await tema.Controllers.CitaController.ObtenerListaTecnicos(), "Seleccione una opción", new { @class = "form-control" })
                        <span asp-validation-for="IDTecnico" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Cliente (el nombre corresponde a la cédula registrada en el sistema)</label>
                        @Html.DropDownListFor(x => x.cedulaCliente, await tema.Controllers.CitaController.ObtenerListaClientes(), "Seleccione una opción", new { @class = "form-control" })
                        <span asp-validation-for="cedulaCliente" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="fecha" class="control-label"></label>
                        <input asp-for="fecha" type="date" class="form-control" />
                        <span asp-validation-for="fecha" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="hora" class="control-label"></label>
                        <input asp-for="hora" type="time" class="form-control" /> 
                        <span asp-validation-for="hora" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="asunto" class="control-label"></label>
                        <input asp-for="asunto" class="form-control" />
                        <span asp-validation-for="asunto" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Seleccione la descripción del servicio (si no observa alguna, agregue una en la pantalla principal de <a asp-action="Index">citas</a>)</label>
                        @Html.DropDownListFor(x => x.descripcion, await tema.Controllers.CitaController.ObtenerListaServicios(), "Seleccione una opción", new { @class = "form-control" })
                        <span asp-validation-for="descripcion" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="citaConfirmada" /> @*@Html.DisplayNameFor(model => model.citaConfirmada)*@ ¿Cita confirmada?
                        </label>
                    </div>

                    <input type="submit" value="Crear" class="Boton" />&nbsp;|
                    <a asp-action="Index" class="Boton">Regresar</a>

                </form>
            </div>
        </div>
     </div>
</div>

tema/Views/Cita/Index.cshtml
@model tema.Models.ViewModels.CitaViewModel

@{
    ViewData["Title"] = "Index";
}

<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<div class="content-wrapper">

    <div class="container">
        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a class="active" style="color:aliceblue">Citas</a></li>
            @*<li><a class="active" style="color:aliceblue">/ Crear Cita</a></li>*@
            @*<li><a href="#">Home</a></li>
                <li><a href="#">Private</a></li>
                <li><a href="#">Pictures</a></li>
                <li class="active">Vacation</li>*@
        </ol>
        <h1>Módulo de citas</h1>

        @section ScriptTablaCita
        {
            <script>
                $(document).ready(function () {
                    $('#tablaDatosCita').DataTable({
                        "language":
                        {
                            "sProcessing": "Procesando...",
                            "sLengthMenu": "Mostrar _MENU_ registros",
                            "sZeroRecords": "No se encontraron resultados",
                            "sEmptyTable": "Ningún dato disponible en esta tabla",
                            "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                            "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                            "sInfoPostFix": "",
                            "sSearch": "Buscar:",
                            "sUrl": "",
                            "sInfoThousands": ",",
                            "sLoadingRecords": "Cargando...",
                            "oPaginate": {
                                "sFirst": "Primero",
                                "sLast": "Último",
                                "sNext": "Siguiente",
                                "sPrevious": "Anterior"
                            },
                            "oAria": {
                                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                            },
                            "buttons": {
                                "copy": "Copiar",
                                "print": "Imprimir",
                                "colvis": "Visibilidad"
                            }
                        },
                        "lengthChange": false,
                        "pageLength": 4
                    });
                });
            </script>
        }
    <table id="tablaDatosCita" class="table table-responsive-md display">
        <thead>
            <tr>
                <th style="color:white">
                    <font size="3">Código del técnico</font>
                </th>
                <th style="color:white">
                    <font size="3">  Cédula del cliente</font>
                </th>
                <th style="color:white">
                    <font size="3"> Fecha de la cita</font>
                </th>
                <th style="color:white">
                    <font size="3">  Hora de la cita</font>
                </th>
                <th style="color:white">
                    <font size="3"> Asunto</font>
                </th>
                <th style="color:white">
                    <font size="3">  Descripción</font>
                </th>
                <th style="color:white">
                    <font size="3"> ¿Está confirmada?</font>
                </th>
                <th style="color:white">
                    <font size="3">  Acciones</font>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Cita citas in Model.cita)
            {
                <tr>
                    <td>
                        @citas.IDTecnico
                    </td>
                    <td>
                        @citas.cedulaCliente
                    </td>
                    <td>
                        @citas.fecha?.Date.ToString("dd/MM/yyyy")
                    </td>
                    <td>
                        @citas.hora
                    </td>
                    <td>
                        @citas.asunto
                    </td>
                    <td>
                        @citas.descripcion
                    </td>
                    <td>
                        @{
                            if (citas.citaConfirmada == true)
                            { <p>Sí</p> }
                            else
                            { <p>No</p> }
                        }
                    </td>
                    <td>
                        <a asp-action="Edit" asp-controller="Cita" asp-route-id="@citas.IDCita">Actualizar</a> |
                        <a asp-action="Delete" asp-controller="Cita" asp-route-id="@citas.IDCita">Cancelar cita</a> |
                        @if (citas.citaConfirmada == true)
                        {
                            <p>
                                @Html.ActionLink("Crear orden", "CreateOrden", "Cita", new { idCita = citas.IDCita, idCliente = citas.IDCliente, desc = citas.descripcion })
                            </p>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
        <p>
            Acciones rápidas:<br />
            <a asp-controller="Cita" asp-action="Create"class="Boton">Crear cita</a> |
            <a asp-controller="Orden" asp-action="Index" class="Boton">Ver órdenes generadas</a>
        </p>
        <hr />
        <h4>Detalle de servicios</h4>
        <p style="text-align: justify;">
            La siguiente tabla le permitirá agregar información preliminar sobre las tareas que debe hacer
            a un vehículo. Le recomendamos que proceda a ingresar servicios antes de crear una cita
            para automatizar la recolección de información dentro de la creación de citas.
        </p>
        <br />
        @section ScriptTablaServicio
        {
            <script>
                $(document).ready(function () {
                    $('#tablaDatosServicio').DataTable({
                        "language":
                        {
                            "sProcessing": "Procesando...",
                            "sLengthMenu": "Mostrar _MENU_ registros",
                            "sZeroRecords": "No se encontraron resultados",
                            "sEmptyTable": "Ningún dato disponible en esta tabla",
                            "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                            "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                            "sInfoPostFix": "",
                            "sSearch": "Buscar:",
                            "sUrl": "",
                            "sInfoThousands": ",",
                            "sLoadingRecords": "Cargando...",
                            "oPaginate": {
                                "sFirst": "Primero",
                                "sLast": "Último",
                                "sNext": "Siguiente",
                                "sPrevious": "Anterior"
                            },
                            "oAria": {
                                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                            },
                            "buttons": {
                                "copy": "Copiar",
                                "colvis": "Visibilidad"
                            }
                        },
                        "paging": false,
                        "scrollY": 150
                    });
                });
            </script>
        }
    <table id="tablaDatosServicio" class="table table-responsive-md">
        <thead>
            <tr>
                <th style="color:white">
                    <font size="3"> Código del vehículo</font>
                </th>
                <th style="color:white">
                    <font size="3">  Descripción del servicio</font>
                </th>
                <th style="color:white">
                    <font size="3">  Acciones</font>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Servicio srv in Model.servicio)
            {
                <tr>
                    <td>
                        @srv.IDVehiculo
                    </td>
                    <td>
                        @srv.descripcion
                    </td>
                    <td>
                        @Html.ActionLink("Actualizar", "Edit", "Servicio", new { id = srv.IDServicio }) |
                        @Html.ActionLink("Eliminar", "Delete", "Servicio", new { id = srv.IDServicio })
                    </td>
                </tr>
            }
        </tbody>
    </table>
        <hr />
        <p >Acciones rápidas:</p><br />
        <a asp-controller="Servicio" asp-action="Create" class="Boton">Crear servicio</a>
    </div>
</div>