tema/Models/DetallesCliente.cs
using System.ComponentModel.DataAnnotations;

namespace tema.Models
{
    public class DetallesCliente
    {
        public int IDCliente { get; set; }
        [Display(Name = "Dirección")]
        [Required(ErrorMessage = "Debe ingresar una dirección")]
        public string direccion { get; set; }
        [Display(Name = "Número telefónico")]
        [StringLength(25, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string telefono { get; set; }
        [Display(Name = "Correo")]
        [EmailAddress(ErrorMessage = "No se ingresó un correo válido")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Debe ingresar el correo")]
        [StringLength(35, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string correo { get; set; }
        public int codDet { get; set; }
        [StringLength(25, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string telefonoExt { get; set; }
    }
}

tema/Controllers/DetallesClienteController.cs
using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using tema.Models;
using tema.Models.ViewModels;

namespace tema.Controllers
{
    [Authorize]
    public class DetallesClienteController : Controller
    {
        string baseurl = "https://localhost:44300/";
        public ActionResult Create()
        {
            return View();
        }

        [TempData]
        public string Message { get; set; }

        [HttpPost]
        public ActionResult Create(int id, [Bind("IDCliente,direccion,telefono,telefonoExt,correo")] DetallesCliente dtc)
        {
            DetallesCliente dtcPost;
            string tel = string.Empty;
            if (string.IsNullOrEmpty(dtc.telefono) && !string.IsNullOrEmpty(dtc.telefonoExt)) tel = dtc.telefonoExt; 
            if (!string.IsNullOrEmpty(dtc.telefono) && string.IsNullOrEmpty(dtc.telefonoExt)) tel = dtc.telefono; 
            else if(tel == string.Empty) ModelState.AddModelError("", "El campo de teléfono está vacío"); 
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    dtcPost = new DetallesCliente
                    {
                        IDCliente = id,
                        direccion = dtc.direccion,
                        telefono = tel,
                        correo = dtc.correo
                    };
                    client.BaseAddress = new Uri(baseurl);
                    var myContent = JsonConvert.SerializeObject(dtcPost);
                    var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                    var byteContent = new ByteArrayContent(buffer);
                    byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    var postTask = client.PostAsync("Taller/Cliente/RegistrarDetallesCliente", byteContent).Result;
                    var result = postTask;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Details", "Cliente");
                    }

                    if(result.StatusCode == HttpStatusCode.InternalServerError)
                    {
                        ModelState.AddModelError(string.Empty, "El correo o el teléfono ya existen para otro cliente");
                    }
                }
            }
            return View(dtc);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var dtc = await GetDetalleEdit(id, new DtcEditViewModel());
            if (dtc == null) return NotFound();
            return View(dtc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, [Bind("IDCliente,direccion,telefono,correo,codDet")] DtcEditViewModel dtc)
        {
            if (id != dtc.codDet)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                DetallesCliente dtcPatch = new DetallesCliente
                {
                    IDCliente = dtc.IDCliente,
                    direccion = dtc.direccion,
                    telefono = dtc.telefono,
                    correo = dtc.correo,
                    codDet = dtc.codDet
                };
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(baseurl);
                    var myContent = JsonConvert.SerializeObject(dtcPatch);
                    var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                    var byteContent = new ByteArrayContent(buffer);
                    byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    var postTask = client.PatchAsync("Taller/Cliente/ActualizarDetalles/" + id, byteContent).Result;
                    var result = postTask;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index", "Cliente");
                    }

                    if (result.StatusCode == HttpStatusCode.InternalServerError)
                    {
                        ModelState.AddModelError(string.Empty, "El correo o el teléfono ya existen para otro cliente");
                    }
                }
            }
            return View(dtc);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return null;
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(baseurl);
                    var deleteTask = client.DeleteAsync
                        (
                            "Taller/Cliente/BorrarDetallesCliente/" + id
                        );
                    deleteTask.Wait();
                }
            }
            return RedirectToAction("Index", "Cliente");
        }

        #region consultas
        private async Task<DetallesCliente> GetDetalle(int? id, DetallesCliente aux)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync
                    (
                        "Taller/Cliente/ObtenerDetalleIndividual/" + id
                    );
                if (res.IsSuccessStatusCode)
                {
                    var auxRes = res.Content.ReadAsStringAsync().Result;

                    aux = JsonConvert.DeserializeObject<DetallesCliente>(auxRes);
                }
            }
            return aux;
        }

        private async Task<DtcEditViewModel> GetDetalleEdit(int? id, DtcEditViewModel aux)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync
                    (
                        "Taller/Cliente/ObtenerDetalleIndividual/" + id
                    );
                if (res.IsSuccessStatusCode)
                {
                    var auxRes = res.Content.ReadAsStringAsync().Result;

                    aux = JsonConvert.DeserializeObject<DtcEditViewModel>(auxRes);
                }
            }
            return aux;
        }
        #endregion consultas
    }
}

tema/Views/DetallesCliente/Create.cshtml
@model tema.Models.DetallesCliente

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js" onload="window.$ = window.jQuery = module.exports;"></script>
<script>
    $(document).ready(function () {
        $("select").change(function () {
            $("select option:selected").each(function () {
                if ($(this).attr("value") == "nac") {
                    $("#extranjero").addClass("d-none");
                    $("#ninguna").addClass("d-none");
                    $("#nacional").removeClass("d-none");
                    $('#boton_guardar').addClass("d-none");
                    $('#numero_ext').val("");
                }
                if ($(this).attr("value") == "ext") {
                    $("#nacional").addClass("d-none");
                    $("#ninguna").addClass("d-none");
                    $("#extranjero").removeClass("d-none");
                    $('#boton_guardar').removeClass("d-none");
                    $('#numero_nac').val("");
                }
                if ($(this).attr("value") == "escoja") {
                    $("#nacional").addClass("d-none");
                    $("#extranjero").addClass("d-none");
                    $("#ninguna").removeClass("d-none");
                    $('#boton_guardar').addClass("d-none");
                    $('#numero_nac').val("");
                    $('#numero_ext').val("");
                }
            });
        }).change();
    });

    $(document).ready(function () {
        var $regexname = /(506-[0-9]{4}-[0-9]{4})/;
        $('#numero_nac').on('keypress keydown keyup mouseout mouseover', function () {
            if (!$(this).val().match($regexname)) {
                $('#error_msg').removeClass('d-none');
                $('#error_msg').addClass('text-danger');
                $('#boton_guardar').addClass('d-none');
            }
            else {
                $('#error_msg').addClass('d-none');
                $('#error_msg').removeClass('text-danger');
                $('#boton_guardar').removeClass('d-none');
            }
        });
    });
</script>
<div class="content-wrapper">
    <div class="container">
        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a asp-controller="DetallesCliente" asp-action="Index" style="color:aliceblue">Detalles del cliente&nbsp;/&nbsp;</a></li>
            <li><a class="active" style="color:aliceblue">Crear nuevo detalle del cliente</a></li>
        </ol>
        <h1>Ingresar información</h1>
        <h4>Detalles del cliente</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-controller="DetallesCliente" asp-action="Create" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="direccion" class="control-label"></label>
                        <input asp-for="direccion" type="text" class="form-control" /> <!--dirección-->
                        <span asp-validation-for="direccion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="telefono" class="control-label"></label>
                        <div>
                            <select class="form-control">
                                <!--Bloque selección de validaciones-->
                                <option value="escoja">Escoja el formato</option>
                                <option value="nac">Nacional (con formato)</option>
                                <option value="ext">Extranjero (sin formato)</option>
                            </select>
                        </div>
                        <div id="ninguna" class="d-none">
                            <label class="control-label text-danger">No se seleccionó ninguna opción</label>
                        </div>
                        <div id="nacional" class="d-none">
                            <!--Nacional-->
                            <label class="control-label">Ingrese un número nacional</label>
                            <input id="numero_nac" asp-for="telefono" type="text" class="form-control" />
                            <p><span id="error_msg" class="text-danger d-none">Formato inválido (ingrese el número así: 506-0000-0000)</span></p>
                        </div>
                        <div id="extranjero" class="d-none">
                            <!--Extranjero-->
                            <label class="control-label">Ingrese un número extranjero</label>
                            <input id="numero_ext" asp-for="telefonoExt" type="text" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="correo" class="control-label"></label>
                        <input asp-for="correo" type="text" class="form-control" /> <!--Correo-->
                        <span asp-validation-for="correo" class="text-danger"></span>
                    </div>
                    <div>
                        <button id="boton_guardar" type="submit" class="Boton d-none">Guardar</button>&nbsp;|
                        <a asp-controller="Cliente" asp-action="Details" class="Boton">Regresar</a>
                    </div>
                </form>
            </div>
        </div>

        
    </div>
</div>

tema/Views/DetallesCliente/Delete.cshtml
@model tema.Models.DetallesCliente

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<div class="content-wrapper">
    <div class="container">



        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a asp-controller="DetallesCliente" asp-action="Index" style="color:aliceblue">Detalles del cliente&nbsp;/&nbsp;</a></li>
            <li><a class="active" style="color:aliceblue">Eliminar un detalle del cliente</a></li>
            @*<li><a href="#">Home</a></li>
                <li><a href="#">Private</a></li>
                <li><a href="#">Pictures</a></li>
                <li class="active">Vacation</li>*@
        </ol>
        <h1>Borrar</h1>

        <h3>¿Desea eliminar esta información?</h3>
        <div>
            <h4>DetallesCliente</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.IDCliente)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.IDCliente)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.direccion)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.direccion)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.telefono)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.telefono)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.correo)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.correo)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="submit" value="Borrar" class="btn btn-danger" /> |
                <a asp-controller="Cliente" asp-action="Index">Regresar</a>
            </form>
        </div>

    </div>
</div>

tema/Views/DetallesCliente/Edit.cshtml
@model tema.Models.ViewModels.DtcEditViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<div class="content-wrapper">
    <div class="container">



        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a asp-controller="DetallesCliente" asp-action="Index" style="color:aliceblue">Detalles del cliente&nbsp;/&nbsp;</a></li>
            <li><a class="active" style="color:aliceblue">Actualizar detalles cliente</a></li>
            @*<li><a href="#">Home</a></li>
                <li><a href="#">Private</a></li>
                <li><a href="#">Pictures</a></li>
                <li class="active">Vacation</li>*@
        </ol>
        <h1>Actualizar</h1>

        <h4>Detalles del cliente</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group" hidden>
                        <label asp-for="IDCliente" class="control-label"></label>
                        <input asp-for="IDCliente" type="text" class="form-control" />
                        <span asp-validation-for="IDCliente" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="direccion" class="control-label"></label>
                        <input asp-for="direccion" class="form-control" />
                        <span asp-validation-for="direccion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="telefono" class="control-label"></label>
                        <input asp-for="telefono" class="form-control" />
                        <span asp-validation-for="telefono" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="correo" class="control-label"></label>
                        <input asp-for="correo" class="form-control" />
                        <span asp-validation-for="correo" class="text-danger"></span>
                    </div>
                    <div class="form-group" hidden>
                        <label asp-for="codDet" class="control-label"></label>
                        <input asp-for="codDet" type="text" class="form-control" />
                        <span asp-validation-for="codDet" class="text-danger"></span>
                    </div>

                    <input type="submit" value="Actualizar" class="Boton" />&nbsp;|
                    <a asp-controller="Cliente" class="Boton" asp-action="Details">Regresar</a>
                </form>
            </div>
        </div>

     </div>
</div>