tema/Models/Vehiculo.cs
using System.ComponentModel.DataAnnotations;

namespace tema.Models
{
    public class Vehiculo
    {
        public string cedclt{ get; set; }
        public int IDVehiculo { get; set; }
        public int IDCliente { get; set; }
        [Display(Name = "Marca y estilo del vehículo")]
        [Required(ErrorMessage = "Debe proveer un valor para este campo")]
        public string marca { get; set; }
        [Required(ErrorMessage = "Se requiere el modelo del vehículo")]
        [Display(Name = "Modelo del vehículo")]
        [RegularExpression(@"^[0-9]{1,4}$", ErrorMessage = "Solo puede ingresar números enteros, máximo 4")] // (?:19|20)\d{2}  /^$/
        public int modelo { get; set; }
        public string placa { get; set; }
        
    }

    public class VehiculoEdit
    {
        public int IDVehiculo { get; set; }

        [Display(Name = "Marca del vehículo")]
        [Required(ErrorMessage = "Debe proveer un valor para este campo")]
        public string marca { get; set; }
        [Required(ErrorMessage = "Se requiere el modelo del vehículo")]
        [Display(Name = "Modelo del vehículo")]
        [RegularExpression(@"^(?:19|20)\d{2}$", ErrorMessage = "Se ha ingresado un modelo inválido. El rango va desde el año 1899 hasta el 2099")]
        public string modelo { get; set; }
        public string placa { get; set; }
    }
}

tema/Models/ViewModels/VehiculoViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace tema.Models.ViewModels
{
    public class VehiculoViewModel
    {
        public List<Cliente> cliente { get; set; }

        #region propieadesCrear
        public string cedclt { get; set; }
        [Required(ErrorMessage = "Se requiere de un nombre descriptivo para este vehículo")]
        [Display(Name = "Estilo")]
        [StringLength(70, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string marca { get; set; }
        [Required(ErrorMessage = "Se requiere el modelo del vehículo")]
        [Display(Name = "Modelo del vehículo")]
        [RegularExpression(@"^(?:19|20)\d{2}$", ErrorMessage = "Se ha ingresado un modelo inválido. El rango va desde el año 1899 hasta el 2099")]
        public string modelo { get; set; }
        //[Required(ErrorMessage = "La placa es obligatoria para agregar un nuevo vehículo")]
        [StringLength(10, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string placa { get; set; }
        [StringLength(10, ErrorMessage = "El nombre ingresado excede el límite de caracteres permitido")]
        public string placaExt { get; set; }
        #nullable enable
        [Required(ErrorMessage = "Debe seleccionar una marca")]
        public string? fabricante { get; set; }
        #nullable disable
        #endregion propieadesCrear
    }
}

tema/Controllers/VehiculoController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using tema.Models;
using tema.Models.ViewModels;
using tema.Utilidades;

namespace tema.Controllers
{
    [Authorize]
    public class VehiculoController : Controller
    {
        string baseurl = "https://localhost:44300/";

        public async Task<IActionResult> Index()
        {
            List<Vehiculo> aux = new List<Vehiculo>();
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync("Taller/Vehiculo/ListaVehiculos");
                if (res.IsSuccessStatusCode) aux = JsonConvert.DeserializeObject<List<Vehiculo>>(res.Content.ReadAsStringAsync().Result);
            }
            return View(aux);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == string.Empty) return NotFound();
            Vehiculo Vehiculo = await GetOneById(id, new Vehiculo());
            if (Vehiculo == null) return NotFound();
            return View(Vehiculo);
        }

        public static List<SelectListItem> ObtenerMarcas()
        {
            List<SelectListItem> ls = new List<SelectListItem>();
            List<string> marcas = ListaFabricantes.ObtenerMarcas();
            foreach(string x in marcas)
            {
                ls.Add(new SelectListItem() { Text = x.ToString(), Value = x.ToString() });
            }
            return ls;
        }

        public static async Task<List<SelectListItem>> ObtenerLista()
        {
            List<SelectListItem> ls = new List<SelectListItem>();
            HttpClient cliente = new HttpClient();
            cliente.BaseAddress = new Uri("https://localhost:44300/");
            cliente.DefaultRequestHeaders.Clear();
            cliente.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resVehiculo = await cliente.GetAsync("Taller/Cliente/ListaClientes");
            List<Cliente> clt = JsonConvert.DeserializeObject<List<Cliente>>(await resVehiculo.Content.ReadAsStringAsync());
            foreach (Cliente temp in clt)
            {
                ls.Add(new SelectListItem() { Text = temp.nombre, Value = temp.cedula });
            }
            return ls;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("cedclt,marca,modelo,placa,placaExt,fabricante")] VehiculoViewModel vhlmod)
        {
            string placa = string.Empty;
            if (string.IsNullOrEmpty(vhlmod.placa) && !string.IsNullOrEmpty(vhlmod.placaExt)) placa = vhlmod.placaExt;
            if (!string.IsNullOrEmpty(vhlmod.placa) && string.IsNullOrEmpty(vhlmod.placaExt)) placa = vhlmod.placa;
            else if (placa == string.Empty) ModelState.AddModelError("", "El campo de la placa está vacío");
            else if (string.IsNullOrEmpty(vhlmod.cedclt)) ModelState.AddModelError("", "No se ha seleccionado un cliente");
            if (ModelState.IsValid)
            {
                Vehiculo vhlPatch = new Vehiculo
                {
                    cedclt = vhlmod.cedclt,
                    marca = string.Join(" ", vhlmod.fabricante, vhlmod.marca),
                    modelo = int.Parse(vhlmod.modelo),
                    placa = placa.ToUpper()
                };
                using (HttpClient client = new HttpClient())
                {
                    client.BaseAddress = new Uri(baseurl);
                    string myContent = JsonConvert.SerializeObject(vhlPatch);
                    byte[] buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                    ByteArrayContent byteContent = new ByteArrayContent(buffer);
                    byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    HttpResponseMessage postTask = client.PostAsync("Taller/Vehiculo/RegistrarVehiculo", byteContent).Result;
                    HttpResponseMessage result = postTask;
                    if (result.StatusCode == HttpStatusCode.BadRequest) ModelState.AddModelError(string.Empty, "Existe un vehículo con esta placa");
                    else if(result.IsSuccessStatusCode) return RedirectToAction(nameof(Index));
                }
            }
            return View(vhlmod);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            Vehiculo vehiculo = await ObtenerVehiculoPorId(id, new Vehiculo());
            VehiculoEdit vhledit = new VehiculoEdit
            {
                IDVehiculo = vehiculo.IDVehiculo,
                marca = vehiculo.marca,
                modelo = vehiculo.modelo.ToString(),
                placa = vehiculo.placa
            };
            if (vhledit == null) return NotFound();
            return View(vhledit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("IDVehiculo,marca,modelo,placa")] VehiculoEdit Vehiculo)
        {
            if (id != Vehiculo.IDVehiculo) return NotFound();
            if (ModelState.IsValid)
            {
                using (HttpClient client = new HttpClient())
                {
                    Vehiculo vhlpatch = new Vehiculo
                    {
                        IDVehiculo = Vehiculo.IDVehiculo,
                        marca = Vehiculo.marca,
                        modelo = int.Parse(Vehiculo.modelo),
                        placa = Vehiculo.placa
                    };
                    client.BaseAddress = new Uri(baseurl);
                    string myContent = JsonConvert.SerializeObject(vhlpatch);
                    byte[] buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                    ByteArrayContent byteContent = new ByteArrayContent(buffer);
                    byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    HttpResponseMessage postTask = await client.PatchAsync("Taller/Vehiculo/ActualizarDatos/" + id, byteContent);
                    HttpResponseMessage result = postTask;
                    if (result.IsSuccessStatusCode) return RedirectToAction(nameof(Index));
                }
            }
            return View(Vehiculo);
        }

        [Authorize]
        [Authorize(Roles = "manager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            Vehiculo vehiculo = await ObtenerVehiculoPorId(id, new Vehiculo());
            if (vehiculo == null) return NotFound();
            return View(vehiculo);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Vehiculo vehiculo = await ObtenerVehiculoPorId(id, new Vehiculo());
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseurl);
                string myContent = JsonConvert.SerializeObject(vehiculo);
                byte[] buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                ByteArrayContent byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage postTask = client.DeleteAsync("Taller/Vehiculo/BorrarVehiculo/" + id).Result;
                HttpResponseMessage result = postTask;
                if (result.IsSuccessStatusCode) return RedirectToAction("Index");
            }
            return RedirectToAction(nameof(Index));
        }

        private async Task<Vehiculo> GetOneById(string placa, Vehiculo aux)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync("Taller/Vehiculo/BuscarVehiculo/" + placa);
                if (res.IsSuccessStatusCode) aux = JsonConvert.DeserializeObject<Vehiculo>(res.Content.ReadAsStringAsync().Result);
            }
            return aux;
        }

        private async Task<Vehiculo> ObtenerVehiculoPorId(int? id, Vehiculo aux)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = await client.GetAsync("Taller/Vehiculo/ListaVehiculos");
                if (res.IsSuccessStatusCode)
                {
                    IEnumerable<Vehiculo> coleccionVhl = JsonConvert.DeserializeObject<IEnumerable<Vehiculo>>(res.Content.ReadAsStringAsync().Result);
                    for (int k = 0; k < coleccionVhl.Count(); k++)
                    {
                        IEnumerable<Vehiculo> vhlquery = from vhl in coleccionVhl where vhl.IDVehiculo == id select vhl;
                        aux = vhlquery.First();
                    }
                }
            }
            return aux;
        }
    }
}

tema/Views/Vehiculo/Create.cshtml
@model tema.Models.ViewModels.VehiculoViewModel

@{
    ViewData["Title"] = "Create";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js" onload="window.$ = window.jQuery = module.exports;"></script>
<script>
    $(document).ready(function () {
        $("select").change(function () {
            $("select option:selected").each(function () {
                if ($(this).attr("value") == "nac") {
                    $("#extranjero").addClass("d-none");
                    $("#ninguna").addClass("d-none");
                    $("#nacional").removeClass("d-none");
                    $('#boton_guardar').addClass("d-none");
                    $('#placa_ext').val("");
                }
                if ($(this).attr("value") == "ext") {
                    $("#nacional").addClass("d-none");
                    $("#ninguna").addClass("d-none");
                    $("#extranjero").removeClass("d-none");
                    $('#boton_guardar').removeClass("d-none");
                    $('#placa_nac').val("");
                }
                if ($(this).attr("value") == "escoja") {
                    $("#nacional").addClass("d-none");
                    $("#extranjero").addClass("d-none");
                    $("#ninguna").removeClass("d-none");
                    $('#boton_guardar').addClass("d-none");
                    $('#placa_nac').val("");
                    $('#placa_ext').val("");
                }
            });
        }).change();
    });

    $(document).ready(function () {
        var $regexname = /^[a-zA-Z0-9]{5,6}$/;
        $('#placa_nac').on('keypress keydown keyup mouseout mouseover', function () {
            if (!$(this).val().match($regexname)) {
                $('#error_msg').removeClass('d-none');
                $('#error_msg').addClass('text-danger');
                $('#boton_guardar').addClass('d-none');
            }
            else {
                $('#error_msg').addClass('d-none');
                $('#error_msg').removeClass('text-danger');
                $('#boton_guardar').removeClass('d-none');
            }
        });
    });
</script>
<div class="content-wrapper">
    <div class="container">
        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a asp-controller="Vehiculo" asp-action="Index" style="color:aliceblue">Vehículos&nbsp;/&nbsp;</a></li>
            <li><a class="active" style="color:aliceblue">Crear vehículo</a></li>
            @*<li><a href="#">Home</a></li>
                <li><a href="#">Private</a></li>*@
        </ol>
        <h4>Vehículo</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label class="control-label">Seleccione al cliente al que corresponde el vehículo</label>
                        @Html.DropDownListFor(x => x.cedclt, await tema.Controllers.VehiculoController.ObtenerLista(), "Seleccione una opción", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label class="control-label">Seleccione una marca</label>
                        @Html.DropDownListFor(x => x.fabricante, tema.Controllers.VehiculoController.ObtenerMarcas(), "Seleccione una opción", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label asp-for="marca" class="control-label"></label>
                        <input asp-for="marca" class="form-control" />
                        <span asp-validation-for="marca" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="modelo" class="control-label"></label>
                        <input asp-for="modelo" type="text" class="form-control" />
                        <span asp-validation-for="modelo" class="text-danger"></span>
                    </div>
                    <!--BLOQUE VALIDACIÓN CÉDULA-->
                    <div class="form-group">
                        <label class="control-label">Placa</label>
                        <div>
                            <select class="form-control">
                                <!--Bloque selección de validaciones-->
                                <option value="escoja">Escoja el formato</option>
                                <option value="nac">Nacional (con formato)</option>
                                <option value="ext">Extranjera (sin formato)</option>
                            </select>
                        </div>
                        <div id="ninguna" class="d-none">
                            <label class="control-label text-danger">No se seleccionó ninguna opción</label>
                        </div>
                        <div id="nacional" class="d-none">
                            <!--Nacional-->
                            <label class="control-label">Ingrese una placa nacional</label>
                            <input id="placa_nac" asp-for="placa" type="text" class="form-control" />
                            <p><span id="error_msg" class="text-danger d-none">Formato inválido (ingrese entre 5 y 6 caracteres incluyendo letras o solo números)</span></p>
                        </div>
                        <div id="extranjero" class="d-none">
                            <!--Extranjera-->
                            <label class="control-label">Ingrese una placa extranjera o con formato diferente</label>
                            <input id="placa_ext" asp-for="placaExt" type="text" class="form-control" />
                        </div>
                    </div>
                    <!--FIN BLOQUE VALIDACIÓN CÉDULA-->
                    <button id="boton_guardar" type="submit" class="Boton d-none">Crear</button>&nbsp;|
                    <a asp-action="Index" class="Boton">Regresar</a>

                </form>
            </div>
        </div>
    </div>
</div>

tema/Views/Vehiculo/Delete.cshtml
@model tema.Models.Vehiculo

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<div class="content-wrapper">
    <div class="container">
        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a asp-controller="Vehiculo" asp-action="Index" style="color:aliceblue">Vehículos&nbsp;/&nbsp;</a></li>
            <li><a class="active" style="color:aliceblue">Eliminar vehículo</a></li>
            @*<li><a href="#">Home</a></li>
                <li><a href="#">Private</a></li>
                <li><a href="#">Pictures</a></li>
                <li class="active">Vacation</li>*@
        </ol>
        <h1>Eliminar vehículo</h1>

        <div>
            <h4>¿Desea proceder con la eliminación de este vehículo?</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2" hidden>
                    @Html.DisplayNameFor(model => model.IDVehiculo)
                </dt>
                <dd class="col-sm-10" hidden>
                    @Html.DisplayFor(model => model.IDVehiculo)
                </dd>
                <dt class="col-sm-2" hidden>
                    @Html.DisplayNameFor(model => model.IDCliente)
                </dt>
                <dd class="col-sm-10" hidden>
                    @Html.DisplayFor(model => model.IDCliente)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.marca)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.marca)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.modelo)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.modelo)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.placa)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.placa)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="submit" value="Eliminar" class="Boton" /> |
                <a asp-action="Index" class="Boton">Regresar</a>
            </form>
        </div>
    </div>
</div>

tema/Views/Vehiculo/Details.cshtml
@model tema.Models.Vehiculo

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<div class="content-wrapper">
    <div class="container">
        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a asp-controller="Vehiculo" asp-action="Index" style="color:aliceblue">Vehículos&nbsp;/&nbsp;</a></li>
            <li><a class="active" style="color:aliceblue">Detalles de vehículo</a></li>
            @*<li><a href="#">Home</a></li>
                <li><a href="#">Private</a></li>
                <li><a href="#">Pictures</a></li>
                <li class="active">Vacation</li>*@
        </ol>
        <h1>Detalles de vehículo</h1>
        <div>
            <hr />
            <dl class="row">
                <dt class="col-sm-2" hidden>
                    @Html.DisplayNameFor(model => model.IDVehiculo)
                </dt>
                <dd class="col-sm-10" hidden>
                    @Html.DisplayFor(model => model.IDVehiculo)
                </dd>
                <dt class="col-sm-2" hidden>
                    @Html.DisplayNameFor(model => model.IDCliente)
                </dt>
                <dd class="col-sm-10" hidden>
                    @Html.DisplayFor(model => model.IDCliente)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.marca)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.marca)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.modelo)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.modelo)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.placa)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.placa)
                </dd>
            </dl>
        </div>
        <div>
            @Html.ActionLink("Editar", "Edit", new { id = Model.IDVehiculo }, new { @class = "Boton" }) |
            <a asp-action="Index" class="Boton">Regresar</a>
        </div>
    </div>
</div>

tema/Views/Vehiculo/Edit.cshtml
@model tema.Models.VehiculoEdit

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />
<div class="content-wrapper">
    <div class="container">
        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a asp-controller="Vehiculo" asp-action="Index" style="color:aliceblue">Vehículos&nbsp;/&nbsp;</a></li>
            <li><a class="active" style="color:aliceblue">Editar vehículo</a></li>
            @*<li><a href="#">Home</a></li>
                <li><a href="#">Private</a></li>
            *@
        </ol>
        <h1>Editar Vehículo</h1>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group" hidden>
                        <label asp-for="IDVehiculo" class="control-label"></label>
                        <input asp-for="IDVehiculo" class="form-control" />
                        <span asp-validation-for="IDVehiculo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="marca" class="control-label"></label>
                        <input asp-for="marca" class="form-control" />
                        <span asp-validation-for="marca" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="modelo" class="control-label"></label>
                        <input asp-for="modelo" type="text" class="form-control" />
                        <span asp-validation-for="modelo" class="text-danger"></span>
                    </div>
                    <div class="form-group" hidden>
                        <label asp-for="placa" class="control-label"></label>
                        <input asp-for="placa" class="form-control" />
                        <span asp-validation-for="placa" class="text-danger"></span>
                    </div>
                    <input type="submit" value="Guardar" class="Boton" />&nbsp;|
                    <a asp-action="Index" class="Boton">Ver lista de vehículos</a>

                </form>
            </div>
        </div>
    </div>
</div>

tema/Views/Vehiculo/Index.cshtml
@model IEnumerable<tema.Models.Vehiculo>
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpAcc

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        font-family: Arial;
    }
</style>
<link href="~/Plantilla/dist/css/Tablas.css" rel="stylesheet" />

<div class="content-wrapper">
    <div class="container">
        <ol class="breadcrumb" style="border:solid;color:black;background-color: #01386E">
            <li><a class="active" style="color:aliceblue">Vehículos</a></li>
            @*<li><a class="active" style="color:aliceblue">Editar Orden</a></li>*@
            @*<li><a href="#">Home</a></li>
                <li><a href="#">Private</a></li>
                <li><a href="#">Pictures</a></li>
                <li class="active">Vacation</li>*@
        </ol>
        <h1>Vehículos</h1>
        @section Scripts
        {
            <script>
                $(document).ready(function () {
                    $('#tablaDatos').DataTable({
                        "language":
                        {
                            "sProcessing": "Procesando...",
                            "sLengthMenu": "Mostrar _MENU_ registros",
                            "sZeroRecords": "No se encontraron resultados",
                            "sEmptyTable": "Ningún dato disponible en esta tabla",
                            "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                            "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                            "sInfoPostFix": "",
                            "sSearch": "Buscar:",
                            "sUrl": "",
                            "sInfoThousands": ",",
                            "sLoadingRecords": "Cargando...",
                            "oPaginate": {
                                "sFirst": "Primero",
                                "sLast": "Último",
                                "sNext": "Siguiente",
                                "sPrevious": "Anterior"
                            },
                            "oAria": {
                                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                            },
                            "buttons": {
                                "copy": "Copiar",
                                "colvis": "Visibilidad"
                            }
                        },
                        "pageLength": 5
                    });
                });
            </script>
        }
    <table id="tablaDatos" class="Tablas" style="width:100%">
        <thead>
            <tr>

                <th style="color:white; font-family:Arial">
                    <font size="3"> @Html.DisplayNameFor(model => model.marca)</font>
                </th>
                <th style="color:white; font-family:Arial;">
                    <font size="3">   @Html.DisplayNameFor(model => model.modelo)</font>
                </th>
                <th style="color:white;font-family:Arial;">
                    <font size="3">  @Html.DisplayNameFor(model => model.placa)</font>
                </th>
                <th class="text-center" style="color:white;font-family:Arial;">
                    <font size="3">    Acciones</font>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.marca)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.modelo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.placa)
                    </td>
                    <td style="text-align:center; font-family:Arial">
                        @Html.ActionLink("Editar", "Edit", new { id = item.IDVehiculo }) |
                        @Html.ActionLink("Detalles", "Details", new { id = item.placa })
                        @if (User.IsInRole("manager"))
                        {
                            @Html.Raw("&#124;&nbsp;") @Html.ActionLink("Eliminar", "Delete", new { id = item.IDVehiculo })
                        } |
                        @Html.ActionLink("Crear expediente", "CreateExpediente", "Expediente", new { id = item.IDVehiculo }) |
                        @Html.ActionLink("Ver expediente", "Details", "Expediente", new { id = item.placa })
                    </td>
                </tr>
            }
        </tbody>
    </table>
        <br />
        <p>
            <a asp-action="Create" class="Boton" style="font-family:Arial; color:white">Registrar vehículo</a>
        </p>
    </div>
</div>